---
require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/schema.rb'
  NewCops: enable
  TargetRubyVersion: 3.1

Metrics/BlockLength:
  IgnoredMethods: ["describe", "context"]
