# frozen_string_literal: true

source 'https://rubygems.org'

ruby '>= 3.1'

gem 'irb', '~> 1.3'
gem 'rake', '~> 13'

gem 'bootsnap', '>= 1.4.4', require: false
gem 'jbuilder', '~> 2.7'
gem 'pg', '~> 1.2'
gem 'puma', '~> 5.0'
gem 'rack-cors'
gem 'rails', '~> 6.1.3', '>= 6.1.3.2'

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'factory_bot_rails'
  gem 'ffaker'
  gem 'rspec-its'
  gem 'rspec-rails', '~> 5'
  gem 'rubocop'
  gem 'rubocop-performance'
  gem 'rubocop-rails_config'
  gem 'rubocop-rake'
  gem 'rubocop-rspec'
  gem 'simplecov', require: false
  gem 'solargraph'
  gem 'yard'
end

group :development do
  gem 'listen', '~> 3.3'
  gem 'spring'
end

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
